### ISSUE TITLE
message is not sent to the right queue

### ISSUE THREAD

**Issue by StonesGitHub** [crabhi/celery-java#10]
I found a bug when testing the main function : the message is always sent to queue 'celery'.
When digging into the code, I found 
`public void send(String queue) throws IOException {
            AMQP.BasicProperties messageProperties = props.headers(headers.map).build();
            channel.basicPublish("", "celery", messageProperties, body);
        }`
the arg 'queue' is actually never used.
#11

**Comment by crabhi** [comment]
Fixed in #11
