### ISSUE TITLE
When Java client calls Java worker, can the worker be deployed on a server separately and not on the same server with Java client?

### ISSUE THREAD

**Issue by zibinwang** [crabhi/celery-java#21]

**Comment by zibinwang** [comment]
When Java client calls Java worker, can the worker be deployed on a server separately and not on the same server with Java client?

**Comment by crabhi** [comment]
I think yes. It should be independent and communicate via message broker. I haven't needed it, though so it's not much tested.

**Comment by zibinwang** [comment]
When Java client calls Java worker, it needs the agent class of worker as the parameter. However, since worker and client are deployed on different servers, how does the client get the agent class of worker?

> I think yes. It should be independent and communicate via message broker. I haven't needed it, though so it's not much tested.

When Java client calls Java worker, it needs the agent class of worker as the parameter. However, since worker and client are deployed on different servers, how does the client get the agent class of worker?

**Comment by crabhi** [comment]
They just need to share the code. The class describes the API of the task and makes it easier to call the task from your code.

Check the [`Celery#submit`](https://github.com/crabhi/celery-java/blob/master/celery-java/src/main/java/com/geneea/celery/Celery.java#L109) method. It just extracts the name from the class. If you really don't want to share the classes, you can use the `Celery#submit(String, Object[])` method.
