### ISSUE TITLE
When i use celery in kotlin i had java.lang.NoClassDefFoundError: com/google/common/collect/Streams

### ISSUE THREAD

**Issue by kubitre** [crabhi/celery-java#22]
![image](https://user-images.githubusercontent.com/32496864/72885902-6bd97680-3d3b-11ea-9950-36b3c0ec17af.png)

**Comment by crabhi** [comment]
Hi, this looks like the library google common isn't part of the runtime classpath. Celery-java needs it to work.

**Comment by kubitre** [comment]
can u say how i can fixed it?

**Comment by crabhi** [comment]
Sorry, no idea about your setup.
